# Generated by Django 4.2.8 on 2023-12-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_cid', models.CharField(default='', max_length=80)),
                ('src', models.CharField(max_length=80)),
                ('dst', models.CharField(max_length=80)),
                ('diversion', models.CharField(default='', max_length=64)),
                ('channel', models.CharField(max_length=80)),
                ('dst_channel', models.CharField(max_length=80)),
                ('start', models.DateTimeField()),
                ('answer', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('duration', models.IntegerField(default=0)),
                ('billsec', models.IntegerField(default=0)),
                ('disposition', models.CharField(max_length=80)),
                ('uniquie_id', models.CharField(max_length=80)),
                ('pbx', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
