# Generated by Django 4.2.8 on 2023-12-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='uniquie_id',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
