# Generated by Django 4.2.8 on 2023-12-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cdr_uniquie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdr',
            name='recpath',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
